name: Flutter CI 

on:
  push: 
    branches:
      - dev
      - test 
      - main # Ou release


jobs: 
  build:
    runs-on: windows-latest

steps:
- name: Checkout code 
  uses: actions/checkout@v2

- name: Set up Flutter
  uses: subosito/flutter-action@v2
  width:
    flutter-version: '2.5.0'

- name: Install dependencies
  run: flutter pub get 

# Passo para carregar variáveis de ambiente baseado na branch
- name: Load environment variables
  run: |
    if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
    cp .env.dev .env
    elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
    cp .env.test .env
    elif [ "${{ github.ref }}" == "refs/heads/main"]; then
    cp .env.release .env
    fi

- name: Run tests
  run: flutter test

- name: Build APK
  run: flutter build apk
